const schedule = {
  "Понеділок": [
    { number: 1, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:00 - 9:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:55 - 10:40" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { uk: "Математика", pl: "Matematyka" }, time: "10:50 - 11:35" },
    { number: " ", subject: { uk: "Обід 1-4 класи", pl: "Obiad klasy 1-4" }, time: "11:35 - 11:55" },
    { number: 4, subject: { uk: "Англійська мова", pl: "Język angielski" }, time: "11:55 - 12:40" },
  ],
  "Вівторок": [
    { number: 1, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:00 - 9:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:55 - 10:40" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { uk: "Математика", pl: "Matematyka" }, time: "10:50 - 11:35" },
    { number: " ", subject: { uk: "Обід 1-4 класи", pl: "Obiad klasy 1-4" }, time: "11:35 - 11:55" },
    { number: 4, subject: { uk: "Przyroda", pl: "Przyroda" }, time: "11:55 - 12:40" },
    { number: " ", subject: { uk: "Обід 5-6 класи", pl: "Obiad klasy 5-6" }, time: "12:40 - 13:00" },
    { number: 5, subject: { uk: "Plastyka", pl: "Plastyka" }, time: "13:00 - 13:45" },
  ],
  "Середа": [
    { number: 1, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:00 - 9:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { uk: "Математика", pl: "Matematyka" }, time: "9:55 - 10:40" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { uk: "Jezyk Polski", pl: "Język polski" }, time: "10:50 - 11:35" },
    { number: " ", subject: { uk: "Обід 1-4 класи", pl: "Obiad klasy 1-4" }, time: "11:35 - 11:55" },
    { number: 4, subject: { uk: "Англійська мова", pl: "Język angielski" }, time: "11:55 - 12:40" },
    { number: " ", subject: { uk: "Обід 5-6 класи", pl: "Obiad klasy 5-6" }, time: "12:40 - 13:00" },
    { number: 5, subject: { uk: "Англійська мова", pl: "Język angielski" }, time: "13:00 - 13:45" },
  ],
  "Четвер": [
    { number: 1, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:00 - 9:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { uk: "Навчання грамоти", pl: "Nauka pisania i czytania" }, time: "9:55 - 10:40" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { uk: "Jezyk Polski", pl: "Język polski" }, time: "10:50 - 11:35" },
    { number: " ", subject: { uk: "Обід 1-4 класи", pl: "Obiad klasy 1-4" }, time: "11:35 - 11:55" },
    { number: 4, subject: { uk: "Математика", pl: "Matematyka" }, time: "11:55 - 12:40" },
    { number: " ", subject: { uk: "Обід 5-6 класи", pl: "Obiad klasy 5-6" }, time: "12:40 - 13:00" },
    { number: 5, subject: { uk: "Plastyka", pl: "Plastyka" }, time: "13:00 - 13:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "13:45 - 13:55" },
    { number: 6, subject: { uk: "Англійська мова", pl: "Język angielski" }, time: "13:55 - 14:40" },
  ],
  "П'ятниця": [
    { number: 1, subject: { uk: "Я досліджую світ", pl: "Poznaję świat" }, time: "9:00 - 9:45" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { uk: "Jezyk Polski", pl: "Język polski" }, time: "9:55 - 10:40" },
    { number: " ", subject: { uk: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { uk: "Edukacja wczesnoszkolna", pl: "Edukacja wczesnoszkolna" }, time: "10:50 - 11:35" },
    { number: " ", subject: { uk: "Обід 1-4 класи", pl: "Obiad klasy 1-4" }, time: "11:35 - 11:55" },
    { number: " ", subject: { uk: "Очікування автобусу", pl: "Oczekiwanie na autobus" }, time: "11:55 - 12:20" },
    { number: " ", subject: { uk: "Шлях зі школи до басейну на автобусі", pl: "Droga ze szkoły na basen autobusem" }, time: "12:20 - 12:45" },
    { number: 4, subject: { uk: "Wyhowanie фізичне (басейн)", pl: "Wychowanie fizyczne (basen)" }, time: "13:00 - 14:00" },
    { number: " ", subject: { uk: "Шлях з басейну до школи на автобусі", pl: "Droga z basenu do szkoły autobusem" }, time: "14:30 - 14:55" },
  ],
};

window.schedule = schedule;
